name: how_to_dywan
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gear/
    - assets/images/glyphs/
    - assets/images/gems/
    - assets/images/professions/
    - assets/images/enchants/
    - assets/images/races/
    - assets/images/rotation/
    - assets/images/talents/affi/
    - assets/images/talents/demo/
    - assets/images/talents/destro/
